### ISSUE TITLE
Logos in Card

### ISSUE THREAD

**Issue by ashutosh887** [ashutosh887/hacktober-2023#62]
Add logos for `mail` and `GitHub` in the Card

**Comment by Gilliash** [comment]
You want to add logos for mail and Github in Usercard? Can you assign this issue to me? I will do my best

**Comment by ashutosh887** [comment]
See we'll upgrade the card design but first let's do one thing.
Add Icon Buttons for `mail` and `github` and show GitHub Username in the Button @Gilliash

**Comment by Gilliash** [comment]
Oke, I can do it.

**Comment by Gilliash** [comment]
So can I take this issue?

Vào 00:56, T.6, 27 Th10, 2023 Ashutosh Jha ***@***.***> đã
viết:

**Comment by ashutosh887** [comment]
Sure go ahead @Gilliash

**Comment by Gilliash** [comment]
Got it, thanks!

Vào 18:03, T.6, 27 Th10, 2023 Ashutosh Jha ***@***.***> đã
viết:

**Comment by Gilliash** [comment]
Hey mate, I made a pull request. Please check it if you have time, thanks!
